/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AIControllerGetSuggestionsParams,
  FeedbackDtoDTO,
  TaskRequestDtoDTO,
} from '.././schemas';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Generate content with intelligent model selection
 */
export const aIControllerGenerateWithTask = (
  taskRequestDtoDTO: TaskRequestDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/generate/task`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: taskRequestDtoDTO,
    signal,
  });
};

export const getAIControllerGenerateWithTaskMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
    TError,
    { data: TaskRequestDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
  TError,
  { data: TaskRequestDtoDTO },
  TContext
> => {
  const mutationKey = ['aIControllerGenerateWithTask'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
    { data: TaskRequestDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerGenerateWithTask(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateWithTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateWithTask>>
>;
export type AIControllerGenerateWithTaskMutationBody = TaskRequestDtoDTO;
export type AIControllerGenerateWithTaskMutationError = unknown;

/**
 * @summary Generate content with intelligent model selection
 */
export const useAIControllerGenerateWithTask = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
    TError,
    { data: TaskRequestDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateWithTask>>,
  TError,
  { data: TaskRequestDtoDTO },
  TContext
> => {
  const mutationOptions = getAIControllerGenerateWithTaskMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get best model for a task without executing
 */
export const aIControllerSelectModel = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/select-model`, method: 'POST', signal });
};

export const getAIControllerSelectModelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerSelectModel>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerSelectModel>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerSelectModel'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerSelectModel>>,
    void
  > = () => {
    return aIControllerSelectModel();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerSelectModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerSelectModel>>
>;

export type AIControllerSelectModelMutationError = unknown;

/**
 * @summary Get best model for a task without executing
 */
export const useAIControllerSelectModel = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerSelectModel>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerSelectModel>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerSelectModelMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get available models for category
 */
export const aIControllerGetModelsForCategory = (category: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/models/${category}`, method: 'GET', signal });
};

export const getAIControllerGetModelsForCategoryQueryKey = (category?: string) => {
  return [`/api/v1/ai/models/${category}`] as const;
};

export const getAIControllerGetModelsForCategoryQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>,
  TError = unknown,
>(
  category: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetModelsForCategoryQueryKey(category);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>> = ({
    signal,
  }) => aIControllerGetModelsForCategory(category, signal);

  return { queryKey, queryFn, enabled: !!category, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetModelsForCategoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>
>;
export type AIControllerGetModelsForCategoryQueryError = unknown;

/**
 * @summary Get available models for category
 */

export function useAIControllerGetModelsForCategory<
  TData = Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>,
  TError = unknown,
>(
  category: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetModelsForCategory>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetModelsForCategoryQueryOptions(category, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Submit feedback on AI output
 */
export const aIControllerRecordFeedback = (
  feedbackDtoDTO: FeedbackDtoDTO,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/feedback`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: feedbackDtoDTO,
    signal,
  });
};

export const getAIControllerRecordFeedbackMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
    TError,
    { data: FeedbackDtoDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
  TError,
  { data: FeedbackDtoDTO },
  TContext
> => {
  const mutationKey = ['aIControllerRecordFeedback'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
    { data: FeedbackDtoDTO }
  > = props => {
    const { data } = props ?? {};

    return aIControllerRecordFeedback(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerRecordFeedbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerRecordFeedback>>
>;
export type AIControllerRecordFeedbackMutationBody = FeedbackDtoDTO;
export type AIControllerRecordFeedbackMutationError = unknown;

/**
 * @summary Submit feedback on AI output
 */
export const useAIControllerRecordFeedback = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
    TError,
    { data: FeedbackDtoDTO },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerRecordFeedback>>,
  TError,
  { data: FeedbackDtoDTO },
  TContext
> => {
  const mutationOptions = getAIControllerRecordFeedbackMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get user preferred models for category
 */
export const aIControllerGetUserPreferences = (category: string, signal?: AbortSignal) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/preferences/${category}`,
    method: 'GET',
    signal,
  });
};

export const getAIControllerGetUserPreferencesQueryKey = (category?: string) => {
  return [`/api/v1/ai/preferences/${category}`] as const;
};

export const getAIControllerGetUserPreferencesQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
  TError = unknown,
>(
  category: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
      TError,
      TData
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetUserPreferencesQueryKey(category);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetUserPreferences>>> = ({
    signal,
  }) => aIControllerGetUserPreferences(category, signal);

  return { queryKey, queryFn, enabled: !!category, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetUserPreferencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetUserPreferences>>
>;
export type AIControllerGetUserPreferencesQueryError = unknown;

/**
 * @summary Get user preferred models for category
 */

export function useAIControllerGetUserPreferences<
  TData = Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
  TError = unknown,
>(
  category: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof aIControllerGetUserPreferences>>,
      TError,
      TData
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetUserPreferencesQueryOptions(category, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get model statistics
 */
export const aIControllerGetModelStats = (
  modelId: string,
  category: string,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/stats/${modelId}/${category}`,
    method: 'GET',
    signal,
  });
};

export const getAIControllerGetModelStatsQueryKey = (modelId?: string, category?: string) => {
  return [`/api/v1/ai/stats/${modelId}/${category}`] as const;
};

export const getAIControllerGetModelStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetModelStats>>,
  TError = unknown,
>(
  modelId: string,
  category: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetModelStats>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAIControllerGetModelStatsQueryKey(modelId, category);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetModelStats>>> = ({
    signal,
  }) => aIControllerGetModelStats(modelId, category, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(modelId && category),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetModelStats>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type AIControllerGetModelStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetModelStats>>
>;
export type AIControllerGetModelStatsQueryError = unknown;

/**
 * @summary Get model statistics
 */

export function useAIControllerGetModelStats<
  TData = Awaited<ReturnType<typeof aIControllerGetModelStats>>,
  TError = unknown,
>(
  modelId: string,
  category: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetModelStats>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetModelStatsQueryOptions(modelId, category, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Generate 5 content ideas/storylines
 */
export const aIControllerGenerateIdeas = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/generate/ideas`, method: 'POST', signal });
};

export const getAIControllerGenerateIdeasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerGenerateIdeas'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
    void
  > = () => {
    return aIControllerGenerateIdeas();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateIdeasMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateIdeas>>
>;

export type AIControllerGenerateIdeasMutationError = unknown;

/**
 * @summary Generate 5 content ideas/storylines
 */
export const useAIControllerGenerateIdeas = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateIdeas>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerGenerateIdeasMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate social media caption
 */
export const aIControllerGenerateCaption = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/generate/caption`, method: 'POST', signal });
};

export const getAIControllerGenerateCaptionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerGenerateCaption'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
    void
  > = () => {
    return aIControllerGenerateCaption();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateCaptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateCaption>>
>;

export type AIControllerGenerateCaptionMutationError = unknown;

/**
 * @summary Generate social media caption
 */
export const useAIControllerGenerateCaption = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateCaption>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerGenerateCaptionMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate attention-grabbing hooks
 */
export const aIControllerGenerateHooks = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/generate/hooks`, method: 'POST', signal });
};

export const getAIControllerGenerateHooksMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerGenerateHooks'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
    void
  > = () => {
    return aIControllerGenerateHooks();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateHooksMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateHooks>>
>;

export type AIControllerGenerateHooksMutationError = unknown;

/**
 * @summary Generate attention-grabbing hooks
 */
export const useAIControllerGenerateHooks = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateHooks>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerGenerateHooksMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Generate SEO hashtags
 */
export const aIControllerGenerateHashtags = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/ai/generate/hashtags`, method: 'POST', signal });
};

export const getAIControllerGenerateHashtagsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['aIControllerGenerateHashtags'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
    void
  > = () => {
    return aIControllerGenerateHashtags();
  };

  return { mutationFn, ...mutationOptions };
};

export type AIControllerGenerateHashtagsMutationResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGenerateHashtags>>
>;

export type AIControllerGenerateHashtagsMutationError = unknown;

/**
 * @summary Generate SEO hashtags
 */
export const useAIControllerGenerateHashtags = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof aIControllerGenerateHashtags>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAIControllerGenerateHashtagsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get AI suggestions for timing and trends
 */
export const aIControllerGetSuggestions = (
  params: AIControllerGetSuggestionsParams,
  signal?: AbortSignal,
) => {
  return customAxiosInstance<void>({
    url: `/api/v1/ai/suggestions`,
    method: 'GET',
    params,
    signal,
  });
};

export const getAIControllerGetSuggestionsQueryKey = (
  params?: AIControllerGetSuggestionsParams,
) => {
  return [`/api/v1/ai/suggestions`, ...(params ? [params] : [])] as const;
};

export const getAIControllerGetSuggestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof aIControllerGetSuggestions>>,
  TError = unknown,
>(
  params: AIControllerGetSuggestionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetSuggestions>>, TError, TData>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAIControllerGetSuggestionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof aIControllerGetSuggestions>>> = ({
    signal,
  }) => aIControllerGetSuggestions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof aIControllerGetSuggestions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AIControllerGetSuggestionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof aIControllerGetSuggestions>>
>;
export type AIControllerGetSuggestionsQueryError = unknown;

/**
 * @summary Get AI suggestions for timing and trends
 */

export function useAIControllerGetSuggestions<
  TData = Awaited<ReturnType<typeof aIControllerGetSuggestions>>,
  TError = unknown,
>(
  params: AIControllerGetSuggestionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof aIControllerGetSuggestions>>, TError, TData>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAIControllerGetSuggestionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
