/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Get user profile
 */
export const usersControllerGetProfile = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/users/profile`, method: 'GET', signal });
};

export const getUsersControllerGetProfileQueryKey = () => {
  return [`/api/v1/users/profile`] as const;
};

export const getUsersControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetProfile>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerGetProfile>>> = ({
    signal,
  }) => usersControllerGetProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetProfile>>
>;
export type UsersControllerGetProfileQueryError = unknown;

/**
 * @summary Get user profile
 */

export function useUsersControllerGetProfile<
  TData = Awaited<ReturnType<typeof usersControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof usersControllerGetProfile>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update user profile
 */
export const usersControllerUpdateProfile = () => {
  return customAxiosInstance<void>({ url: `/api/v1/users/profile`, method: 'PATCH' });
};

export const getUsersControllerUpdateProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerUpdateProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    void
  > = () => {
    return usersControllerUpdateProfile();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>
>;

export type UsersControllerUpdateProfileMutationError = unknown;

/**
 * @summary Update user profile
 */
export const useUsersControllerUpdateProfile = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateProfile>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerUpdateProfileMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete user account
 */
export const usersControllerDeleteAccount = () => {
  return customAxiosInstance<void>({ url: `/api/v1/users/account`, method: 'DELETE' });
};

export const getUsersControllerDeleteAccountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['usersControllerDeleteAccount'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
    void
  > = () => {
    return usersControllerDeleteAccount();
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerDeleteAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerDeleteAccount>>
>;

export type UsersControllerDeleteAccountMutationError = unknown;

/**
 * @summary Delete user account
 */
export const useUsersControllerDeleteAccount = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerDeleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getUsersControllerDeleteAccountMutationOptions(options);

  return useMutation(mutationOptions);
};
