/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import type { UpdateBusinessProfileDtoDTOBusinessType } from './updateBusinessProfileDtoDTOBusinessType';

export interface UpdateBusinessProfileDtoDTO {
  /** Business name */
  businessName?: string;
  /** Business type */
  businessType?: UpdateBusinessProfileDtoDTOBusinessType;
  /** Business description */
  businessDescription?: string;
}
