/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Business Pro API
 * AI-driven social media automation platform for local businesses
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customAxiosInstance } from '.././axios-instance';

/**
 * @summary Health check endpoint
 */
export const appControllerGetHealth = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1`, method: 'GET', signal });
};

export const getAppControllerGetHealthQueryKey = () => {
  return [`/api/v1`] as const;
};

export const getAppControllerGetHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetHealth>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHealth>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHealth>>> = ({ signal }) =>
    appControllerGetHealth(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetHealth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerGetHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHealth>>
>;
export type AppControllerGetHealthQueryError = unknown;

/**
 * @summary Health check endpoint
 */

export function useAppControllerGetHealth<
  TData = Awaited<ReturnType<typeof appControllerGetHealth>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHealth>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerGetHealthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Alternative health check endpoint
 */
export const appControllerHealthCheck = (signal?: AbortSignal) => {
  return customAxiosInstance<void>({ url: `/api/v1/health`, method: 'GET', signal });
};

export const getAppControllerHealthCheckQueryKey = () => {
  return [`/api/v1/health`] as const;
};

export const getAppControllerHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerHealthCheck>>> = ({
    signal,
  }) => appControllerHealthCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerHealthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerHealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerHealthCheck>>
>;
export type AppControllerHealthCheckQueryError = unknown;

/**
 * @summary Alternative health check endpoint
 */

export function useAppControllerHealthCheck<
  TData = Awaited<ReturnType<typeof appControllerHealthCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof appControllerHealthCheck>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
